development:
  adapter: postgresql
  encoding: utf8
  database: whorunit_development
  host: localhost

staging:
  adapter: postgresql
  encoding: utf8
  database: whorunit_staging
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: whorunit_test
  host: localhost
